language: node_js
sudo: false

matrix:
  include:
    - node_js: "0.10"
      env: KARMA=false
    - node_js: "node"
      env: KARMA=
    - node_js: "iojs"
      env: KARMA=false

cache:
  directories:
    - node_modules
